# Generated by Django 4.1.1 on 2022-10-04 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0003_collection_username_alter_collection_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
