# Generated by Django 4.1.1 on 2022-10-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0006_remove_movie_id_alter_movie_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
