# Generated by Django 4.1.1 on 2022-10-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0007_meta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
